name: Build & Test

on: [pull_request]

jobs:
  build:
    strategy:
      matrix:
        go: ["1.23"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout code into the Go module directory
        uses: actions/checkout@v3
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
